# Generated by Django 2.0.6 on 2018-10-26 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('arttitle', models.CharField(max_length=20, verbose_name='标题')),
                ('artauthor', models.CharField(max_length=20, null=True, verbose_name='作者名称')),
                ('artdesc', models.CharField(max_length=500, verbose_name='文章简介')),
                ('artcontent', models.TextField(verbose_name='文章内容')),
                ('artdate', models.CharField(max_length=50, verbose_name='发表时间')),
                ('artimg', models.CharField(max_length=200, null=True, verbose_name='图片链接')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'fz_news',
            },
        ),
        migrations.CreateModel(
            name='Articletype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=20, verbose_name='文章类型')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'db_table': 'fz_newstype',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comcontent', models.TextField()),
                ('comdate', models.DateField(auto_now_add=True)),
                ('comart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Article')),
                ('comuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
                'db_table': 'fz_newscomment',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='arttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Articletype', verbose_name='文章类型'),
        ),
    ]
