# Generated by Django 2.0.6 on 2018-10-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='artdate',
            field=models.CharField(max_length=50, null=True, verbose_name='发表时间'),
        ),
    ]
