# Generated by Django 2.0.6 on 2018-10-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20181026_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='article',
            name='update_time',
        ),
    ]
