# Generated by Django 2.0.6 on 2018-10-29 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_relationartuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ManyToManyField(null=True, through='news.Relationartuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
