# Generated by Django 2.0.6 on 2018-10-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comdate',
        ),
        migrations.AddField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=2, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除标记'),
        ),
        migrations.AddField(
            model_name='comment',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
