# Generated by Django 2.0.6 on 2018-10-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20181030_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='update_time',
        ),
    ]
