# Generated by Django 2.0.6 on 2018-10-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('jokecontent', models.CharField(max_length=100, verbose_name='笑话内容')),
                ('jokeauthor', models.CharField(max_length=50, verbose_name='作者名称')),
                ('jokeimg', models.ImageField(upload_to='jokeimg', verbose_name='笑话图片')),
            ],
            options={
                'verbose_name': '笑话',
                'verbose_name_plural': '笑话',
                'db_table': 'fz_joke',
            },
        ),
        migrations.CreateModel(
            name='Joketype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('typename', models.CharField(max_length=20, verbose_name='笑话分类')),
            ],
            options={
                'verbose_name': '笑话分类',
                'verbose_name_plural': '笑话分类',
                'db_table': 'fz_joketype',
            },
        ),
        migrations.AddField(
            model_name='joke',
            name='joketype',
            field=models.ForeignKey(on_delete=True, to='jokes.Joketype', verbose_name='分类'),
        ),
    ]
