# Generated by Django 2.0.6 on 2018-10-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_auto_20181025_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='joke',
            name='update_time',
        ),
    ]
