# Generated by Django 2.0.6 on 2018-10-29 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jokes', '0003_auto_20181029_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationjokeuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joke', models.ForeignKey(on_delete=True, to='jokes.Joke')),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='joke',
            name='user',
            field=models.ManyToManyField(null=True, through='jokes.Relationjokeuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
