# Generated by Django 2.0.6 on 2018-10-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imgdet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('imgname', models.CharField(max_length=50, verbose_name='图集名称')),
                ('detimg', models.ImageField(upload_to='igmdet', verbose_name='图集详情图')),
            ],
            options={
                'verbose_name': '图片详情页',
                'verbose_name_plural': '图片详情页',
                'db_table': 'fz_imgdet',
            },
        ),
        migrations.CreateModel(
            name='Imgmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('imgname', models.CharField(max_length=50, verbose_name='图集名称')),
                ('mainimg', models.ImageField(upload_to='imgmain', verbose_name='图集主图')),
            ],
            options={
                'verbose_name': '图片主页',
                'verbose_name_plural': '图片主页',
                'db_table': 'fz_imgmain',
            },
        ),
        migrations.AddField(
            model_name='imgdet',
            name='mainimg',
            field=models.ForeignKey(on_delete=True, to='imgshow.Imgmain', verbose_name='图片详情'),
        ),
    ]
