# Generated by Django 2.0.6 on 2018-10-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgshow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgmain',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='imgmain',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='imgmain',
            name='update_time',
        ),
        migrations.AddField(
            model_name='imgmain',
            name='imgtype',
            field=models.IntegerField(default=2, verbose_name='图片类型'),
            preserve_default=False,
        ),
    ]
