# Generated by Django 2.0.6 on 2018-10-25 03:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goodsdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('goodsname', models.CharField(max_length=50, verbose_name='商品名称')),
                ('goodsprice', models.IntegerField(verbose_name='商品价格')),
                ('goodscon', tinymce.models.HTMLField(blank=True, verbose_name='商品简介')),
                ('goodsimg', models.ImageField(upload_to='goodsdet')),
            ],
            options={
                'verbose_name': '商品详情',
                'verbose_name_plural': '商品详情',
                'db_table': 'fz_goodsdet',
            },
        ),
        migrations.CreateModel(
            name='Goodsmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('goodsname', models.CharField(max_length=50, verbose_name='商品名称')),
                ('goodsmainimg', models.ImageField(upload_to='goodsmain')),
            ],
            options={
                'verbose_name': '主商品',
                'verbose_name_plural': '主商品',
                'db_table': 'fz_goodsmain',
            },
        ),
        migrations.CreateModel(
            name='Goodstype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('typename', models.CharField(max_length=50, verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'fz_goodstype',
            },
        ),
        migrations.AddField(
            model_name='goodsmain',
            name='goodst',
            field=models.ForeignKey(on_delete=True, to='goods.Goodstype', verbose_name='商品属分类'),
        ),
        migrations.AddField(
            model_name='goodsdetail',
            name='goodsid',
            field=models.ForeignKey(on_delete=True, to='goods.Goodsmain', verbose_name='商品主页'),
        ),
    ]
