# Generated by Django 2.0.6 on 2018-10-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsdetail',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='goodsdetail',
            name='goodsid',
        ),
        migrations.RemoveField(
            model_name='goodsdetail',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='goodsdetail',
            name='update_time',
        ),
        migrations.AddField(
            model_name='goodsdetail',
            name='goodst',
            field=models.ForeignKey(default=2, on_delete=True, to='goods.Goodstype', verbose_name='商品属分类'),
            preserve_default=False,
        ),
    ]
