# Generated by Django 2.0.6 on 2018-10-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181029_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetail',
            name='goodsprice',
            field=models.CharField(max_length=50, verbose_name='商品价格'),
        ),
    ]
