# Generated by Django 2.0.6 on 2018-10-31 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181030_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsdetail',
            name='goodscon',
        ),
    ]
