# Generated by Django 2.0.6 on 2018-10-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_remove_goodsdetail_goodscon'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdetail',
            name='goodscon',
            field=models.TextField(blank=True, verbose_name='商品简介'),
        ),
    ]
